/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ObtenerSesionActual$Params {
}

export function obtenerSesionActual(http: HttpClient, rootUrl: string, params?: ObtenerSesionActual$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'email': string;
'id': string;
'nombre': string;
'rol': 'admin' | 'asesor';
}>> {
  const rb = new RequestBuilder(rootUrl, obtenerSesionActual.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'email': string;
      'id': string;
      'nombre': string;
      'rol': 'admin' | 'asesor';
      }>;
    })
  );
}

obtenerSesionActual.PATH = '/api/v1/auth/yo';
