/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GuardarMensajeFijo$Params {
  clave: string;
      body: {
'texto': string;
}
}

export function guardarMensajeFijo(http: HttpClient, rootUrl: string, params: GuardarMensajeFijo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'actualizado': (string | null);
'clave': string;
'descripcion': string;
'origen': 'base' | 'respaldo';
'texto': string;
}>> {
  const rb = new RequestBuilder(rootUrl, guardarMensajeFijo.PATH, 'put');
  if (params) {
    rb.path('clave', params.clave, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'actualizado': (string | null);
      'clave': string;
      'descripcion': string;
      'origen': 'base' | 'respaldo';
      'texto': string;
      }>;
    })
  );
}

guardarMensajeFijo.PATH = '/api/v1/mensajes-fijos/{clave}';
