/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListarMensajesFijos$Params {
}

export function listarMensajesFijos(http: HttpClient, rootUrl: string, params?: ListarMensajesFijos$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'mensajes': Array<{
'actualizado': (string | null);
'clave': string;
'descripcion': string;
'origen': 'base' | 'respaldo';
'texto': string;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, listarMensajesFijos.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'mensajes': Array<{
      'actualizado': (string | null);
      'clave': string;
      'descripcion': string;
      'origen': 'base' | 'respaldo';
      'texto': string;
      }>;
      }>;
    })
  );
}

listarMensajesFijos.PATH = '/api/v1/mensajes-fijos';
