/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CrearCaso$Params {
      body: {
'activo'?: boolean;
'categoriaId': string;
'claveSistema'?: (string | null);
'cuandoAplica'?: string;
'modo'?: 'literal' | 'guia';
'texto': string;
'titulo': string;
}
}

export function crearCaso(http: HttpClient, rootUrl: string, params: CrearCaso$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'activo': boolean;
'actualizado': string;
'categoriaId': string;
'categoriaNombre': string;
'claveSistema': (string | null);
'creado': string;
'cuandoAplica': string;
'disparador': 'evento' | 'intencion';
'id': string;
'modo': 'literal' | 'guia';
'texto': string;
'titulo': string;
}>> {
  const rb = new RequestBuilder(rootUrl, crearCaso.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'activo': boolean;
      'actualizado': string;
      'categoriaId': string;
      'categoriaNombre': string;
      'claveSistema': (string | null);
      'creado': string;
      'cuandoAplica': string;
      'disparador': 'evento' | 'intencion';
      'id': string;
      'modo': 'literal' | 'guia';
      'texto': string;
      'titulo': string;
      }>;
    })
  );
}

crearCaso.PATH = '/api/v1/asistente/casos';
