/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListarCasos$Params {
  q?: string;
  categoriaId?: string;
  disparador?: 'evento' | 'intencion';
  activo?: 'true' | 'false';
  cursor?: string;
  limite?: number;
}

export function listarCasos(http: HttpClient, rootUrl: string, params?: ListarCasos$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items': Array<{
'activo': boolean;
'actualizado': string;
'categoriaId': string;
'categoriaNombre': string;
'claveSistema': (string | null);
'creado': string;
'cuandoAplica': string;
'disparador': 'evento' | 'intencion';
'id': string;
'modo': 'literal' | 'guia';
'texto': string;
'titulo': string;
}>;
'siguienteCursor': (string | null);
}>> {
  const rb = new RequestBuilder(rootUrl, listarCasos.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('categoriaId', params.categoriaId, {});
    rb.query('disparador', params.disparador, {});
    rb.query('activo', params.activo, {});
    rb.query('cursor', params.cursor, {});
    rb.query('limite', params.limite, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items': Array<{
      'activo': boolean;
      'actualizado': string;
      'categoriaId': string;
      'categoriaNombre': string;
      'claveSistema': (string | null);
      'creado': string;
      'cuandoAplica': string;
      'disparador': 'evento' | 'intencion';
      'id': string;
      'modo': 'literal' | 'guia';
      'texto': string;
      'titulo': string;
      }>;
      'siguienteCursor': (string | null);
      }>;
    })
  );
}

listarCasos.PATH = '/api/v1/asistente/casos';
