/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListarCategoriasCaso$Params {
}

export function listarCategoriasCaso(http: HttpClient, rootUrl: string, params?: ListarCategoriasCaso$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'categorias': Array<{
'id': string;
'nombre': string;
'orden': number;
'totalCasos': number;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, listarCategoriasCaso.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'categorias': Array<{
      'id': string;
      'nombre': string;
      'orden': number;
      'totalCasos': number;
      }>;
      }>;
    })
  );
}

listarCategoriasCaso.PATH = '/api/v1/asistente/categorias';
