/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RenombrarCategoriaCaso$Params {
  id: string;
      body: {
'nombre': string;
}
}

export function renombrarCategoriaCaso(http: HttpClient, rootUrl: string, params: RenombrarCategoriaCaso$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'id': string;
'nombre': string;
'orden': number;
'totalCasos': number;
}>> {
  const rb = new RequestBuilder(rootUrl, renombrarCategoriaCaso.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'id': string;
      'nombre': string;
      'orden': number;
      'totalCasos': number;
      }>;
    })
  );
}

renombrarCategoriaCaso.PATH = '/api/v1/asistente/categorias/{id}';
