/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ObtenerEstilo$Params as ObtenerEstilo$Params } from './fn/estilo/obtener-estilo';
export { obtenerEstilo as obtenerEstilo } from './fn/estilo/obtener-estilo';
export type { PublicarEstilo$Params as PublicarEstilo$Params } from './fn/estilo/publicar-estilo';
export { publicarEstilo as publicarEstilo } from './fn/estilo/publicar-estilo';
export type { ListarHistorialEstilo$Params as ListarHistorialEstilo$Params } from './fn/estilo/listar-historial-estilo';
export { listarHistorialEstilo as listarHistorialEstilo } from './fn/estilo/listar-historial-estilo';
export type { RestaurarEstilo$Params as RestaurarEstilo$Params } from './fn/estilo/restaurar-estilo';
export { restaurarEstilo as restaurarEstilo } from './fn/estilo/restaurar-estilo';
export type { IniciarSesion$Params as IniciarSesion$Params } from './fn/auth/iniciar-sesion';
export { iniciarSesion as iniciarSesion } from './fn/auth/iniciar-sesion';
export type { CerrarSesion$Params as CerrarSesion$Params } from './fn/auth/cerrar-sesion';
export { cerrarSesion as cerrarSesion } from './fn/auth/cerrar-sesion';
export type { ObtenerSesionActual$Params as ObtenerSesionActual$Params } from './fn/auth/obtener-sesion-actual';
export { obtenerSesionActual as obtenerSesionActual } from './fn/auth/obtener-sesion-actual';
export type { ListarMensajesFijos$Params as ListarMensajesFijos$Params } from './fn/mensajes-fijos/listar-mensajes-fijos';
export { listarMensajesFijos as listarMensajesFijos } from './fn/mensajes-fijos/listar-mensajes-fijos';
export type { GuardarMensajeFijo$Params as GuardarMensajeFijo$Params } from './fn/mensajes-fijos/guardar-mensaje-fijo';
export { guardarMensajeFijo as guardarMensajeFijo } from './fn/mensajes-fijos/guardar-mensaje-fijo';
