/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface BorrarExcepcionHorario$Params {
  fecha: string;
}

export function borrarExcepcionHorario(http: HttpClient, rootUrl: string, params: BorrarExcepcionHorario$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, borrarExcepcionHorario.PATH, 'delete');
  if (params) {
    rb.path('fecha', params.fecha, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

borrarExcepcionHorario.PATH = '/api/v1/configuracion/horario/excepciones/{fecha}';
