/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CrearExcepcionHorario$Params {
      body: {
'fecha': string;
'motivo'?: (string | null);
}
}

export function crearExcepcionHorario(http: HttpClient, rootUrl: string, params: CrearExcepcionHorario$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'fecha': string;
'motivo': (string | null);
}>> {
  const rb = new RequestBuilder(rootUrl, crearExcepcionHorario.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'fecha': string;
      'motivo': (string | null);
      }>;
    })
  );
}

crearExcepcionHorario.PATH = '/api/v1/configuracion/horario/excepciones';
