/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GuardarConfiguracionEnvios$Params {
      body: {
'factorVolumetrico': number;
'recargoContraentregaPct': number;
[key: string]: any;
}
}

export function guardarConfiguracionEnvios(http: HttpClient, rootUrl: string, params: GuardarConfiguracionEnvios$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'actualizado': (string | null);
'factorVolumetrico': number;
'recargoContraentregaPct': number;
}>> {
  const rb = new RequestBuilder(rootUrl, guardarConfiguracionEnvios.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'actualizado': (string | null);
      'factorVolumetrico': number;
      'recargoContraentregaPct': number;
      }>;
    })
  );
}

guardarConfiguracionEnvios.PATH = '/api/v1/configuracion/envios';
