/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GuardarHorario$Params {
      body: {
'dias': {
'dom': ({
'desde': string;
'hasta': string;
} | null);
'jue': ({
'desde': string;
'hasta': string;
} | null);
'lun': ({
'desde': string;
'hasta': string;
} | null);
'mar': ({
'desde': string;
'hasta': string;
} | null);
'mie': ({
'desde': string;
'hasta': string;
} | null);
'sab': ({
'desde': string;
'hasta': string;
} | null);
'vie': ({
'desde': string;
'hasta': string;
} | null);
};
[key: string]: any;
}
}

export function guardarHorario(http: HttpClient, rootUrl: string, params: GuardarHorario$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'actualizado': (string | null);
'dias': {
'dom': ({
'desde': string;
'hasta': string;
} | null);
'jue': ({
'desde': string;
'hasta': string;
} | null);
'lun': ({
'desde': string;
'hasta': string;
} | null);
'mar': ({
'desde': string;
'hasta': string;
} | null);
'mie': ({
'desde': string;
'hasta': string;
} | null);
'sab': ({
'desde': string;
'hasta': string;
} | null);
'vie': ({
'desde': string;
'hasta': string;
} | null);
};
'excepciones': Array<{
'fecha': string;
'motivo': (string | null);
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, guardarHorario.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'actualizado': (string | null);
      'dias': {
      'dom': ({
      'desde': string;
      'hasta': string;
      } | null);
      'jue': ({
      'desde': string;
      'hasta': string;
      } | null);
      'lun': ({
      'desde': string;
      'hasta': string;
      } | null);
      'mar': ({
      'desde': string;
      'hasta': string;
      } | null);
      'mie': ({
      'desde': string;
      'hasta': string;
      } | null);
      'sab': ({
      'desde': string;
      'hasta': string;
      } | null);
      'vie': ({
      'desde': string;
      'hasta': string;
      } | null);
      };
      'excepciones': Array<{
      'fecha': string;
      'motivo': (string | null);
      }>;
      }>;
    })
  );
}

guardarHorario.PATH = '/api/v1/configuracion/horario';
