/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GuardarGastoLlm$Params {
      body: {
'techoMensualUsd': number;
[key: string]: any;
}
}

export function guardarGastoLlm(http: HttpClient, rootUrl: string, params: GuardarGastoLlm$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'actualizado': (string | null);
'estado': ({
'avisoEmitido': boolean;
'bloqueado': boolean;
'mes': string;
} | null);
'gastoMesUsd': (number | null);
'techoMensualUsd': (number | null);
}>> {
  const rb = new RequestBuilder(rootUrl, guardarGastoLlm.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'actualizado': (string | null);
      'estado': ({
      'avisoEmitido': boolean;
      'bloqueado': boolean;
      'mes': string;
      } | null);
      'gastoMesUsd': (number | null);
      'techoMensualUsd': (number | null);
      }>;
    })
  );
}

guardarGastoLlm.PATH = '/api/v1/configuracion/gasto-llm';
