/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ObtenerConfiguracionEnvios$Params {
}

export function obtenerConfiguracionEnvios(http: HttpClient, rootUrl: string, params?: ObtenerConfiguracionEnvios$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'actualizado': (string | null);
'factorVolumetrico': number;
'recargoContraentregaPct': number;
}>> {
  const rb = new RequestBuilder(rootUrl, obtenerConfiguracionEnvios.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'actualizado': (string | null);
      'factorVolumetrico': number;
      'recargoContraentregaPct': number;
      }>;
    })
  );
}

obtenerConfiguracionEnvios.PATH = '/api/v1/configuracion/envios';
