/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface CrearSeccionEstilo$Params {
      body: {
'activo'?: boolean;
'texto': string;
'titulo': string;
}
}

export function crearSeccionEstilo(http: HttpClient, rootUrl: string, params: CrearSeccionEstilo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'activo': boolean;
'actualizado': string;
'id': string;
'orden': number;
'texto': string;
'titulo': string;
}>> {
  const rb = new RequestBuilder(rootUrl, crearSeccionEstilo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'activo': boolean;
      'actualizado': string;
      'id': string;
      'orden': number;
      'texto': string;
      'titulo': string;
      }>;
    })
  );
}

crearSeccionEstilo.PATH = '/api/v1/agente/estilo/secciones';
