/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ListarSeccionesEstilo$Params {
}

export function listarSeccionesEstilo(http: HttpClient, rootUrl: string, params?: ListarSeccionesEstilo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'caracteresCompuestos': number;
'maximo': number;
'secciones': Array<{
'activo': boolean;
'actualizado': string;
'id': string;
'orden': number;
'texto': string;
'titulo': string;
}>;
}>> {
  const rb = new RequestBuilder(rootUrl, listarSeccionesEstilo.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'caracteresCompuestos': number;
      'maximo': number;
      'secciones': Array<{
      'activo': boolean;
      'actualizado': string;
      'id': string;
      'orden': number;
      'texto': string;
      'titulo': string;
      }>;
      }>;
    })
  );
}

listarSeccionesEstilo.PATH = '/api/v1/agente/estilo/secciones';
