/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ObtenerEstilo$Params {
}

export function obtenerEstilo(http: HttpClient, rootUrl: string, params?: ObtenerEstilo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'origen': 'base' | 'archivo';
'publicadoPor': ({
'id': string;
'nombre': string;
} | null);
'texto': string;
'version': (number | null);
}>> {
  const rb = new RequestBuilder(rootUrl, obtenerEstilo.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'origen': 'base' | 'archivo';
      'publicadoPor': ({
      'id': string;
      'nombre': string;
      } | null);
      'texto': string;
      'version': (number | null);
      }>;
    })
  );
}

obtenerEstilo.PATH = '/api/v1/agente/estilo';
