/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RestaurarEstilo$Params {
      body: {
'version': number;
}
}

export function restaurarEstilo(http: HttpClient, rootUrl: string, params: RestaurarEstilo$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'version': number;
}>> {
  const rb = new RequestBuilder(rootUrl, restaurarEstilo.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'version': number;
      }>;
    })
  );
}

restaurarEstilo.PATH = '/api/v1/agente/estilo/restauraciones';
